-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departamentos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT departamentos_pkey PRIMARY KEY (id),
    CONSTRAINT departamentos_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.informes_tecnicos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp with time zone NOT NULL DEFAULT now(),
    fecha_actualizacion timestamp with time zone,
    fecha_cierre timestamp with time zone,
    id_solicitante bigint NOT NULL,
    id_tecnico bigint,
    descripcion_equipo text COLLATE pg_catalog."default" NOT NULL,
    diagnostico_problema text COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    estado estado_informe NOT NULL DEFAULT 'Pendiente'::estado_informe,
    CONSTRAINT informes_tecnicos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario character varying COLLATE pg_catalog."default" NOT NULL,
    contrasena character varying COLLATE pg_catalog."default" NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    rol rol_usuario NOT NULL,
    cargo character varying COLLATE pg_catalog."default" NOT NULL,
    id_departamento bigint NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_usuario_key UNIQUE (usuario)
);

ALTER TABLE IF EXISTS public.informes_tecnicos
    ADD CONSTRAINT informes_tecnicos_id_solicitante_fkey FOREIGN KEY (id_solicitante)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.informes_tecnicos
    ADD CONSTRAINT informes_tecnicos_id_tecnico_fkey FOREIGN KEY (id_tecnico)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_id_departamento_fkey FOREIGN KEY (id_departamento)
    REFERENCES public.departamentos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;